### ISSUE TITLE
translation missing error

### ISSUE THREAD

**Issue by friedrichweise** [AfeefaDe/afeefa-backend-api#1]
The example seed data is not conform to the attribute constrains (e.g. description)

````
{"errors":[{"title":"translation missing: de.activerecord.errors.models.orga.attributes.description.too_long","detail":"description - translation missing: de.activerecord.errors.models.orga.attributes.description.too_long","code":"100","source":{"pointer":"/data/attributes/description"},"status":"422"}]}
`````

**Reproduce**
Change state of orga "Gorbitz spielt mit"

**Comment by stevereinke** [comment]
Hier müssen wir ein Konzept erarbeiten. Sollen die Fehler im Backend übersetzt werden  oder im Frontend?

**Comment by stevereinke** [comment]
Ich habe angefangen, Fehler im Backend zu übersetzen. Allerdings werden immer mal wieder unbekannte Übersetzungen zu ergänzen sein (beispielsweise im Zuge der Migration).
